stages:
  - build
  - deploy


variables:
  IMAGE_NAME: livros-api
  CONTAINER_NAME: livros.api

build_image:
  stage:build
  script:
    - echo "Iniciando o build da imagem docker..."
    - docker build -t $IMAGE_NAME:latest .
  tags:
   - docker

deploy_app:
  stage: deploy
  script:
    - echo "Parando containers antigos (se existirem)..."
    - docker compose down || true
    - echo "Subindo nova versao com Docker Compose..."
    - docker compose up -d
  tags:
   - docker
  only:
   -main